# theme: no-style-please
remote_theme: riggraz/no-style-please
title: trashbin
description: "null"
timezone: Asia/Singapore
plugins:
  - jekyll-remote-theme
permalink: /:year/:month/:day/:title:output_ext